from pathlib import Path
from typing import TypeVar, Literal

PathLike = TypeVar("PathLike", str, Path, None)
AtomFormat = Literal["abinit-gsr", "abinit-in", "abinit-out",
                     "aims", "aims-output", "in",
                     "bundletrajectory",
                     "castep-castep", "castep-cell", "castep-geom", "castep-md", "castep-phonon", "castep", "cell", "geom", "md","phonon",
                     "cfg", 
                     "cif", 
                     "cmdft", 
                     "cjson",
                     "cp2k-dcd", "cp2k-restart", "dcd", "restart",
                     "crystal", "f34", "34",
                     "cube",
                     "db",
                     "dftb",
                     "dlp4", "config",
                     "dlp-history",
                     "dmol-arc", "dmol-car", "dmol-incoor", "arc", "car",
                     "elk", "elk-in",
                     "eon", "con",
                     "eps", 
                     "espresso-in", "espresso-out", "pwi", "pwo", "out",
                     "exciting",
                     "extxyz",
                     "findsym",
                     "gamess-us-out", "gamess-us-in", "gamess-us-punch", "dat"
                     "gaussian-in", "gaussian-out", "com", "gjf", "log",
                     "acemolecule-out", "acemolecule-input",
                     "gen",
                     "gif",
                     "gpaw-out",
                     "gpw",
                     "gromacs", "gro",
                     "gromos", "g96",
                     "html",
                     "json",
                     "jsv",
                     "lammps-dump-text", "lammps-dump-binary", "lammps-data",
                     "magres",
                     "mol",
                     "mp4",
                     "mustem", "xtl",
                     "mysql",
                     "netcdftrajectory",
                     "nomad-json",
                     "nwchem-in", "nwchem-out", "nwi", "nwo"
                     "octopus-in", "octopus-out",
                     "onetep-out", "onetep-in",
                     "proteindatabank", "pdb"
                     "png",
                     "postgresql",
                     "pov",
                     "prismatic",
                     "py",
                     "sys",
                     "qbox",
                     "res", "shelx",
                     "rmc6f",
                     "sdf",
                     "siesta-xv",
                     "struct",
                     "struct_out",
                     "traj",
                     "turbomole",
                     "turbomole-gradient",
                     "v-sim",
                     "vasp", "vasp-out", "vasp-xdatcar", "vasp-xml", "poscar",
                     "vti",
                     "vtu",
                     "wout",
                     "x3d",
                     "xsd",
                     "xsf",
                     "xtd",
                     "xyz",
                     ]
